### GET Products
GET http://localhost:8000/v1/products
Content-Type: application/json

### GET Product
GET http://localhost:8000/v1/products/11
Content-Type: application/json

### POST Product
POST http://localhost:8000/v1/products
Content-Type: application/json

{
    "id": "15",
    "name": "Macbook Pro",
    "price": 1449.99
}